### ISSUE TITLE
Possible missing grunt-legacy dependency

### ISSUE THREAD

**Issue by Mingling94** [NebulousLabs/Sia-UI#102]
# OS: Ubuntu 14.10

## sudo npm install produces the following terminal output:
```
npm WARN unmet dependency /home/ming/Documents/Projects/Sia-UI/node_modules/grunt requires coffee-script@'~1.3.3' but will load
npm WARN unmet dependency /home/ming/Documents/Projects/Sia-UI/node_modules/coffee-script,
npm WARN unmet dependency which is version 1.9.2
npm WARN unmet dependency /home/ming/Documents/Projects/Sia-UI/node_modules/grunt-contrib-less requires less@'~2.4.0' but will load
npm WARN unmet dependency /home/ming/Documents/Projects/Sia-UI/node_modules/less,
npm WARN unmet dependency which is version 2.5.0
```
## sudo npm start produces the following terminal output:
```
ming@ming-N56VZ:~/Documents/Projects/Sia-UI$ sudo npm start
> Sia-UI@0.2.0 start /home/ming/Documents/Projects/Sia-UI
> grunt run


module.js:340
    throw err;
          ^
Error: Cannot find module 'grunt-legacy-util'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/ming/Documents/Projects/Sia-UI/node_modules/grunt/lib/grunt.js:26:12)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/lib/node_modules/grunt-cli/bin/grunt:45:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:935:3
```
## and lastly the npm-debug.log is as follows:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@1.4.28
3 info using node@v0.10.38
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart Sia-UI@0.2.0
7 info start Sia-UI@0.2.0
8 verbose unsafe-perm in lifecycle true
9 info Sia-UI@0.2.0 Failed to exec start script
10 error Sia-UI@0.2.0 start: `grunt run`
10 error Exit status 8
11 error Failed at the Sia-UI@0.2.0 start script.
11 error This is most likely a problem with the Sia-UI package,
11 error not with npm itself.
11 error Tell the author that this fails on your system:
11 error     grunt run
11 error You can get their info via:
11 error     npm owner ls Sia-UI
11 error There is likely additional logging output above.
12 error System Linux 3.16.0-34-generic
13 error command "/usr/bin/node" "/usr/bin/npm" "start"
14 error cwd /home/ming/Documents/Projects/Sia-UI
15 error node -v v0.10.38
16 error npm -v 1.4.28
17 error code ELIFECYCLE
18 verbose exit [ 1, true ]
```

**Comment by Mingling94** [comment]
Not sure what happened when I posted this, but on a clean install of Ubuntu 14.04, this worked well enough.
