### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by roymj88** [NebulousLabs/Sia-UI#256]
So i pull in latest from master and try to run `npm start` and things again hit roadblock.

![sia_ui](https://cloud.githubusercontent.com/assets/2633799/16243057/16d3e41c-3813-11e6-92a8-5d9c382ede47.png)

Full error log: 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.8.6
3 info using node@v5.11.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle Sia-UI-beta@0.5.2-beta~prestart: Sia-UI-beta@0.5.2-beta
6 silly lifecycle Sia-UI-beta@0.5.2-beta~prestart: no script for prestart, continuing
7 info lifecycle Sia-UI-beta@0.5.2-beta~start: Sia-UI-beta@0.5.2-beta
8 verbose lifecycle Sia-UI-beta@0.5.2-beta~start: unsafe-perm in lifecycle true
9 verbose lifecycle Sia-UI-beta@0.5.2-beta~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/roy/projects/Sia-UI/node_modules/.bin:/usr/local/bin:/home/roy/.rvm/gems/ruby-2.0.0-p481/bin:/home/roy/.rvm/gems/ruby-2.0.0-p481@global/bin:/home/roy/.rvm/rubies/ruby-2.0.0-p481/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/roy/Roy/android-sdk-linux/tools:/home/roy/Roy/android-sdk-linux/platform-tools:/home/roy/android-sdk-linux/tools:/usr/share/ant/bin:/home/roy/.rvm/bin
10 verbose lifecycle Sia-UI-beta@0.5.2-beta~start: CWD: /home/roy/projects/Sia-UI
11 silly lifecycle Sia-UI-beta@0.5.2-beta~start: Args: [ '-c', 'webpack && electron .' ]
12 silly lifecycle Sia-UI-beta@0.5.2-beta~start: Returned: code: 1  signal: null
13 info lifecycle Sia-UI-beta@0.5.2-beta~start: Failed to exec start script
14 verbose stack Error: Sia-UI-beta@0.5.2-beta start: `webpack && electron .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid Sia-UI-beta@0.5.2-beta
16 verbose cwd /home/roy/projects/Sia-UI
17 error Linux 3.13.0-45-generic
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.11.1
20 error npm  v3.8.6
21 error code ELIFECYCLE
22 error Sia-UI-beta@0.5.2-beta start: `webpack && electron .`
22 error Exit status 1
23 error Failed at the Sia-UI-beta@0.5.2-beta start script 'webpack && electron .'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Sia-UI-beta package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack && electron .
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Sia-UI-beta
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Sia-UI-beta
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Please note that ive switched between versions node 6 and 5.11.1 (6 seems to have lots of issues and 5.11.1 seems to be the stable one)

**Comment by avahowell** [comment]
Not sure if `node 5.11.1` supports `let` and `const`.  Try adding `'use strict'` to the top of `webpack.config.js`.

**Comment by roymj88** [comment]
@johnathanhowell : Boom. Resolved.
