### ISSUE TITLE
Siad has exited unexpectedly.

### ISSUE THREAD

**Issue by guelz** [NebulousLabs/Sia-UI#580]
not sure what to make of this!? 
I updated from 1.1.2 to 1.2.1 through the gui_terminal and then after a ~week siad started crashing without a crash_log. So I overwrote the folder with 1.2.1 and got this error log.

````Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.236631 seconds
unexpected fault address 0x7fff1040
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0x7fff1040 pc=0x72a458]

goroutine 16 [running]:
runtime.throw(0xa9c8c8, 0x5)
	/usr/local/go/src/runtime/panic.go:596 +0x9c fp=0xc0430e6e38 sp=0xc0430e6e18
runtime.sigpanic()

---------------------------------snip---------------------------------------------------


net/http.(*conn).serve(0xc04203c000, 0xd95200, 0xc043120000)
	/usr/local/go/src/net/http/server.go:1825 +0x619
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2d5

goroutine 1042 [IO wait]:
net.runtime_pollWait(0x644b1100, 0x72, 0xd8b568)
	/usr/local/go/src/runtime/netpoll.go:164 +0x60
net.(*pollDesc).wait(0xc04289bbe0, 0x72, 0xd8b568, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x3f
net.(*ioSrv).ExecIO(0xc042004138, 0xc04289baa0, 0xaa0816, 0x7, 0xad4258, 0x0, 0x1, 0xc042ff3f28)
	/usr/local/go/src/net/fd_windows.go:196 +0xfe
net.(*netFD).Read(0xc04289ba40, 0xc043120051, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/fd_windows.go:452 +0x13d
net.(*conn).Read(0xc042194068, 0xc043120051, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:181 +0x77
net/http.(*connReader).backgroundRead(0xc043120040)
	/usr/local/go/src/net/http/server.go:656 +0x5f
created by net/http.(*connReader).startBackgroundRead
	/usr/local/go/src/net/http/server.go:652 +0xe6````

**Comment by lukechampine** [comment]
Actually you got it right the first time, this is a Sia issue :P
This panic comes from the database. Can you try deleting the existing folder and resyncing the blockchain from scratch?
