### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Nickabilla** [NebulousLabs/Sia-UI#584]
This error is thrown on OSX when opening SIA-UI:

```
Uncaught Exception:
Error: EROFS: read-only file system, open '/private/var/folders/_p/wrccvt6d1hv461rd3mktsky00000gn/T/AppTranslocation/0436F1C2-9C1C-46E9-A0BC-B89233D2BC6E/d/Sia-UI.app/Contents/Resources/app/config.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at Object.e.save (/private/var/folders/_p/wrccvt6d1hv461rd3mktsky00000gn/T/AppTranslocation/0436F1C2-9C1C-46E9-A0BC-B89233D2BC6E/d/Sia-UI.app/Contents/Resources/app/dist/main.js:1:10793)
    at o (/private/var/folders/_p/wrccvt6d1hv461rd3mktsky00000gn/T/AppTranslocation/0436F1C2-9C1C-46E9-A0BC-B89233D2BC6E/d/Sia-UI.app/Contents/Resources/app/dist/main.js:1:10888)
    at Object.0 (/private/var/folders/_p/wrccvt6d1hv461rd3mktsky00000gn/T/AppTranslocation/0436F1C2-9C1C-46E9-A0BC-B89233D2BC6E/d/Sia-UI.app/Contents/Resources/app/dist/main.js:1:525)
    at e (/private/var/folders/_p/wrccvt6d1hv461rd3mktsky00000gn/T/AppTranslocation/0436F1C2-9C1C-46E9-A0BC-B89233D2BC6E/d/Sia-UI.app/Contents/Resources/app/dist/main.js:1:262)
    at t.0.t.__esModule.default (/private/var/folders/_p/wrccvt6d1hv461rd3mktsky00000gn/T/AppTranslocation/0436F1C2-9C1C-46E9-A0BC-B89233D2BC6E/d/Sia-UI.app/Contents/Resources/app/dist/main.js:1:349)
    at Object.<anonymous> (/private/var/folders/_p/wrccvt6d1hv461rd3mktsky00000gn/T/AppTranslocation/0436F1C2-9C1C-46E9-A0BC-B89233D2BC6E/d/Sia-UI.app/Contents/Resources/app/dist/main.js:1:354)
    at Object.<anonymous> (/private/var/folders/_p/wrccvt6d1hv461rd3mktsky00000gn/T/AppTranslocation/0436F1C2-9C1C-46E9-A0BC-B89233D2BC6E/d/Sia-UI.app/Contents/Resources/app/dist/main.js:2:3)
```

**Comment by avxkim** [comment]
Doesn't work on MacOS Sierra 10.12.4

**Comment by lukechampine** [comment]
Duplicate of #395
This is fixed in the master branch and will be released shortly. In the meantime, move the app to a different folder before opening.

**Comment by gtrider** [comment]
Has this been released?  Thanks
