### ISSUE TITLE
config.json not found

### ISSUE THREAD

**Issue by stinch** [NebulousLabs/Sia-UI#624]
After downloading and unpacking the git repo, executing Sia-UI gives the following error:

user@host:~/sia-UI$ ./Sia-UI 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/home/user/.config/Sia-UI/config.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at Object.e.save (/home/user/sia-UI/resources/app/dist/main.js:1:2543)
    at r (/home/user/sia-UI/resources/app/dist/main.js:1:2638)
    at Object.<anonymous> (/home/user/sia-UI/resources/app/dist/main.js:1:1241)
    at e (/home/user/sia-UI/resources/app/dist/main.js:1:256)
    at Object.<anonymous> (/home/user/sia-UI/resources/app/dist/main.js:1:14446)
    at e (/home/user/sia-UI/resources/app/dist/main.js:1:256)
    at /home/user/sia-UI/resources/app/dist/main.js:1:637

After creating the file, the program starts successfully:
user@host:~/sia-UI$ touch /home/user/.config/Sia-UI/config.json

Note that the directory /home/user/.config/Sia-UI was created on the first execution of Sia-UI.

version: v1.6.4
host: Ubuntu 16.04.2 LTS, AMD FX-8320E

**Comment by avahowell** [comment]
This was fixed in https://github.com/NebulousLabs/Sia-UI/pull/619, closing for now.
