### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by natv** [NebulousLabs/Sia-UI#659]
I can't open Sia-UI.  I didn't make any changes to it (didn't try to upgrade or anything like that), it's exactly like it was last time I used it (same computer, same folder)

Full error is attached.

I re-downloaded the same version (Sia-UI v1.2.2 )and extracted it to a new folder but it's giving the same error when I open it (after some time).

Is there a different way I can access my wallet for now? I have my password saved can I use this somewhere else to restore the wallet? (if this can't be fixed)

![sia-error](https://user-images.githubusercontent.com/1175232/27889119-6c2674fa-61b8-11e7-9812-9e7cce0c4a48.jpg)

**Comment by dobdob** [comment]
I'm having similar problems. Downloaded 1.2.2 for Windows x64. I managed to create a wallet and started the sync, but had to shutdown my machine part way through. I did right click the tray icon and selected Quit Sia before the shutdown. When I started it up again it showed an upgrade window and then a similar error to the one above.

Restart 1.2.2 after a reboot
![sia-update1](https://user-images.githubusercontent.com/10797087/28221686-897c0de0-68c4-11e7-9703-4925032a0e06.JPG)

Wait a while
![sia-update1-error](https://user-images.githubusercontent.com/10797087/28221705-9e9c62ec-68c4-11e7-9a93-1b8810a5e216.JPG)

**Comment by dobdob** [comment]
Discovered I could scroll down for more info:
```
A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
goroutine 129 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc043f1da78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc043f1dbf0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc057940920, 0xc043f1dbf0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc057938548)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6b0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc057938548)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc057938548, 0xc057944840, 0xc0579448a0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0x149
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0x103
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename C:\Users\XXXX\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal_temp C:\Users\XXXX\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal: Access is denied.
Closing host...
Closing wallet...
Closing transaction pool...
Closing consensus set...
Closing gateway...
invalid argument
```
Appears to be similar: to https://github.com/NebulousLabs/Sia/issues/1651

**Comment by dobdob** [comment]
I had a look at the directory permissions. They look ok to me. I then started Sia-UI up again and the files are created. They appear to be created and deleted during this mysterious upgrade process. Then eventually they are deleted and then the error occurs again.

File are there shortly after startup
![sia-update1-files-exist](https://user-images.githubusercontent.com/10797087/28222880-85805002-68c9-11e7-9679-725607859c1a.JPG)
Files are gone
![sia-update1-files-gone](https://user-images.githubusercontent.com/10797087/28222889-8d94509a-68c9-11e7-8355-c0ed1f797b2b.JPG)
Moments later
![sia-update1-files-gone-error](https://user-images.githubusercontent.com/10797087/28222902-9e3fe940-68c9-11e7-9436-82a17b7653dd.JPG)
