### ISSUE TITLE
Massive Memory Usage

### ISSUE THREAD

**Issue by grigzy28** [NebulousLabs/Sia-UI#686]
After a bit the siad.exe gives the following error and is also taking up 3+ gb of ram and is also making the sia-ui unresponsive and the whole PC comes to a crawl 

```
    /usr/local/go/src/runtime/debug/stack.go:16 +0x29

github.com/NebulousLabs/Sia/build.Severe(0xc044f0ff20, 0x2, 0x2)
/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99

github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc05cb990e0, 0xc042a4

    /home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
    created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
    /home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
    Severe error: api call is taking more than 60 minutes to return: /consensus
    goroutine 33472 [running]:
    runtime/debug.Stack(0x44439e, 0x0, 0xc05cab3e98)
    /usr/local/go/src/runtime/debug/stack.go:24 +0x80
    runtime/debug.PrintStack()
    /usr/local/go/src/runtime/debug/stack.go:16 +0x29
    github.com/NebulousLabs/Sia/build.Severe(0xc05cab3f20, 0x2, 0x2)
    /home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99

github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc05b7d7620, 0xc0432d
2f00)
/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
0
```

**Comment by livanh** [comment]
I experienced similar behavior on Linux, while uploading 3 moderately large files (300 MB - 1 GB) at the same time. My guess is that siad is either not releasing memory after uploading some blocks, or duplicating many many blocks and uploading them in parallel (thus filling system memory). In the latter case, some limitation on RAM usage should be imposed, rather than assuming "infinite" memory.

**Comment by grigzy28** [comment]
Well, I wasn't uploading any files.  I experienced it in the windows UI.

What I think happened was that siad was still syncing the blockchain while I tried to unlock the wallet in the windows UI.  Thus causing the problem with the consensus.  When I used the siac command line client to unlock the wallet it worked fine.

**Comment by krasanen** [comment]
Same problem observed in linux with siad when uploading folder of random files with siac renter upload. 4GB memory was not enough for siad, had to enable swap to make it run. It simply uses too much ram.

**Comment by ronki2304** [comment]
Hello I have the same problem after uploading 15Go, Sia-UI take 10 Go in RAM

I used Sia with duplicati and duplicati become slower and slower after each upload

any news on this topic ?
