### ISSUE TITLE
Error at startup Sia v1.3 (Mac) 

### ISSUE THREAD

**Issue by cuicrypto** [NebulousLabs/Sia-UI#700]
A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
unexpected fault address 0x8c07008
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x8c07008 pc=0x132d3c9]

goroutine 1 [running]:
runtime.throw(0x16d0af7, 0x5)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc4202a9c38 sp=0xc4202a9c18
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:287 +0x1c8 fp=0xc4202a9c88 sp=0xc4202a9c38
github.com/NebulousLabs/bolt.(*Cursor).search(0xc4202aa218, 0xc4202aa2b8, 0x20, 0x20, 0x6f2c)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:255 +0x69 fp=0xc4202a9d50 sp=0xc4202a9c88
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc4202aa218, 0xc4202aa2b8, 0x20, 0x20, 0x29e8000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x156 fp=0xc4202a9de0 sp=0xc4202a9d50
github.com/NebulousLabs/bolt.(*Cursor).search(0xc4202aa218, 0xc4202aa2b8, 0x20, 0x20, 0xd0d)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1bb fp=0xc4202a9ea8 sp=0xc4202a9de0
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc4202aa218, 0xc4202aa2b8, 0x20, 0x20, 0x2a73000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x156 fp=0xc4202a9f38 sp=0xc4202a9ea8
github.com/NebulousLabs/bolt.(*Cursor).search(0xc4202aa218, 0xc4202aa2b8, 0x20, 0x20, 0xd98)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1bb fp=0xc4202aa000 sp=0xc4202a9f38
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc4202aa218, 0xc4202aa2b8, 0x20, 0x20, 0x2a87000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x156 fp=0xc4202aa090 sp=0xc4202aa000
github.com/NebulousLabs/bolt.(*Cursor).search(0xc4202aa218, 0xc4202aa2b8, 0x20, 0x20, 0xdac)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1bb fp=0xc4202aa158 sp=0xc4202aa090
github.com/NebulousLabs/bolt.(*Cursor).seek(0xc4202aa218, 0xc4202aa2b8, 0x20, 0x20, 0x0, 0x0, 0x12de7c3, 0xc4200feb78, 0xc420c97c50, 0x2, ...)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:159 +0xb1 fp=0xc4202aa1a8 sp=0xc4202aa158
github.com/NebulousLabs/bolt.(*Bucket).Get(0xc420cbafc0, 0xc4202aa2b8, 0x20, 0x20, 0xc420cbafc0, 0x361eb3868b7257d3, 0x996b7b2473587e05)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:267 +0xef fp=0xc4202aa248 sp=0xc4202aa1a8
github.com/NebulousLabs/Sia/modules/consensus.getBlockMap(0xc4200feb60, 0xb59f000000000000, 0xeec9c37774615da4, 0x46527690ef7351d6, 0xeea96b2615448c3c, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusdb.go:185 +0x7d fp=0xc4202aa2b0 sp=0xc4202aa248
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).computeConsensusChange(0xc420139b80, 0xc4200feb60, 0x0, 0x0, 0x0, 0xc420c77840, 0x1, 0x1, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:53 +0x818 fp=0xc4202aaeb0 sp=0xc4202aa2b0
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe.func2(0xc4200feb60, 0x17081f0, 0xc4200feb60)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:172 +0xe0 fp=0xc4202ab190 sp=0xc4202aaeb0
github.com/NebulousLabs/bolt.(*DB).View(0xc420100780, 0xc42008f248, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:634 +0x9f fp=0xc4202ab1e0 sp=0xc4202ab190
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe(0xc420139b80, 0x19deca0, 0xc420071080, 0x37de6f2504b8cf98, 0xbd29e1cbe8209d42, 0x5939d4ad8e31f11c, 0xe80f2dee79106f34, 0x14d33c7, 0xa73f115)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:180 +0x24f fp=0xc4202ab2c8 sp=0xc4202ab1e0
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).ConsensusSetSubscribe(0xc420139b80, 0x19deca0, 0xc420071080, 0x37de6f2504b8cf98, 0xbd29e1cbe8209d42, 0x5939d4ad8e31f11c, 0xe80f2dee79106f34, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:203 +0xee fp=0xc4202ab370 sp=0xc4202ab2c8
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist(0xc420071080, 0xc420071080, 0xc42025a540)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:183 +0x944 fp=0xc4202ab5a8 sp=0xc4202ab370
github.com/NebulousLabs/Sia/modules/transactionpool.New(0x19ea7c0, 0xc420139b80, 0x19e9ba0, 0xc420070c60, 0xc4200199a0, 0x45, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/transactionpool.go:101 +0x276 fp=0xc4202ab620 sp=0xc4202ab5a8
main.startDaemon(0x0, 0x0, 0x7fff5fbffcdf, 0xe, 0x7fff5fbffd0b, 0x5, 0x7fff5fbffcfa, 0x5, 0x0, 0x7fff5fbffd61, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:202 +0x1693 fp=0xc4202abbd0 sp=0xc4202ab620
main.startDaemonCmd(0xc420079200, 0xc420019360, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:335 +0x162 fp=0xc4202abcd0 sp=0xc4202abbd0
github.com/spf13/cobra.(*Command).execute(0xc420079200, 0xc42000e0d0, 0x5, 0x5, 0xc420079200, 0xc42000e0d0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:653 +0x299 fp=0xc4202abd88 sp=0xc4202abcd0
github.com/spf13/cobra.(*Command).ExecuteC(0xc420079200, 0x16fce88, 0x3b, 0xc420148a00)
	/home/luke/go/src/github.com/spf13/cobra/command.go:728 +0x339 fp=0xc4202abed8 sp=0xc4202abd88
github.com/spf13/cobra.(*Command).Execute(0xc420079200, 0x1aefba0, 0x16e58f7)
	/home/luke/go/src/github.com/spf13/cobra/command.go:687 +0x2b fp=0xc4202abf08 sp=0xc4202abed8
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7aa fp=0xc4202abf88 sp=0xc4202abf08
runtime.main()
	/usr/local/go/src/runtime/proc.go:185 +0x20a fp=0xc4202abfe0 sp=0xc4202abf88
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4202abfe8 sp=0xc4202abfe0

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0xff
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [IO wait]:
net.runtime_pollWait(0x1c60060, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42014ad18, 0x72, 0x0, 0xc420172000)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42014ad18, 0xffffffffffffffff, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc42014acb0, 0x0, 0x19dffe0, 0xc420172000)
	/usr/local/go/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc42000c138, 0xc4201680c0, 0x1616680, 0x1ab94a0)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc42000c138, 0xc420168090, 0x1616680, 0x1ab94a0, 0x166f960)
	/usr/local/go/src/net/tcpsock.go:228 +0x49
net/http.(*Server).Serve(0xc420097080, 0x19e5f20, 0xc42000c138, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2643 +0x228
main.(*Server).Serve(0xc4200bb960, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/server.go:416 +0x44
main.startDaemon.func1(0xc42014c240, 0xc4200bb960)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:145 +0x2b
created by main.startDaemon
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:146 +0x312

goroutine 7 [select]:
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedSaveLoop(0xc420070c60)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/persist.go:57 +0x122
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:249 +0x683

goroutine 8 [IO wait]:
net.runtime_pollWait(0x1c5ffa0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42014af48, 0x72, 0x0, 0xc4201d0000)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42014af48, 0xffffffffffffffff, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc42014aee0, 0x0, 0x19dffe0, 0xc4201d0000)
	/usr/local/go/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc42000c168, 0xc400000008, 0xc4201ce000, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc42000c168, 0x1708c50, 0xc42014c300, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock.go:228 +0x49
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentListen(0xc420070c60, 0xc42014c300)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:99 +0x75
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:294 +0xa23

goroutine 9 [select]:
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedSleep(0xc420070c60, 0x12a05f200, 0xc4201c2060)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:164 +0x121
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentPeerManager(0xc420070c60, 0xc42014c360)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peersmanager.go:153 +0x608
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:301 +0xacf

goroutine 10 [select]:
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentNodeManager(0xc420070c60, 0xc42014c3c0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/nodes.go:283 +0x5e0
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:308 +0xb7b

goroutine 11 [select]:
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentNodePurger(0xc420070c60, 0xc42014c420)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/nodes.go:221 +0x650
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:315 +0xc27

goroutine 12 [sleep]:
time.Sleep(0xb61799c0)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/NebulousLabs/go-upnp.Discover(0xc400000008, 0x17081b0, 0xc420070d48)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/upnp.go:129 +0x55
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedForwardPort(0xc420070c60, 0xc42013ac15, 0x4)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/upnp.go:97 +0x8b
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:318 +0xc5e

goroutine 13 [sleep]:
time.Sleep(0xd2b3d1c0)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/NebulousLabs/go-upnp.Discover(0xc400000008, 0x17081b0, 0xc420070d48)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/upnp.go:129 +0x55
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedLearnHostname(0xc420070c60)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/upnp.go:59 +0x8e
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:319 +0xc83

goroutine 33 [IO wait]:
net.runtime_pollWait(0x1c5fee0, 0x77, 0xc4201cc4c0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420228068, 0x77, 0xc4201cc4f8, 0x1191899)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitWrite(0xc420228068, 0x1708700, 0x19e6b20)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x34
net.(*netFD).connect(0xc420228000, 0x19e6b20, 0xc4201c0200, 0x0, 0x0, 0x19e0220, 0xc4201c4060, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:156 +0x24e
net.(*netFD).dial(0xc420228000, 0x19e6b20, 0xc4201c0200, 0x19e8a80, 0x0, 0x19e8a80, 0xc42021e090, 0xc4201cc6e0, 0x11ad88e)
	/usr/local/go/src/net/sock_posix.go:140 +0xe9
net.socket(0x19e6b20, 0xc4201c0200, 0x16ced9e, 0x3, 0x2, 0x1, 0x0, 0x0, 0x19e8a80, 0x0, ...)
	/usr/local/go/src/net/sock_posix.go:92 +0x1a1
net.internetSocket(0x19e6b20, 0xc4201c0200, 0x16ced9e, 0x3, 0x19e8a80, 0x0, 0x19e8a80, 0xc42021e090, 0x1, 0x0, ...)
	/usr/local/go/src/net/ipsock_posix.go:154 +0x129
net.doDialTCP(0x19e6b20, 0xc4201c0200, 0x16ced9e, 0x3, 0x0, 0xc42021e090, 0x1b0c470, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:62 +0xb9
net.dialTCP(0x19e6b20, 0xc4201c0200, 0x16ced9e, 0x3, 0x0, 0xc42021e090, 0xc4201c0200, 0x40, 0x1)
	/usr/local/go/src/net/tcpsock_posix.go:58 +0xe4
net.dialSingle(0x19e6b20, 0xc4201c0200, 0xc420222000, 0x19e33a0, 0xc42021e090, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:521 +0x479
net.dialSerial(0x19e6b20, 0xc4201c0200, 0xc420222000, 0xc4201e2a50, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:489 +0x220
net.(*Dialer).DialContext(0xc4201ccc70, 0x19e6b60, 0xc420016408, 0x16ced9e, 0x3, 0xc420196120, 0x14, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dial.go:371 +0x70b
net.(*Dialer).Dial(0xc4201ccc70, 0x16ced9e, 0x3, 0xc420196120, 0x14, 0x10, 0x10, 0xc79efbd5d5fb9ec7, 0x10)
	/usr/local/go/src/net/dial.go:294 +0x75
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).dial(0xc420070c60, 0xc420196120, 0x14, 0x14, 0x1b0d200, 0x100, 0x12c)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/conn.go:30 +0xc6
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedConnect(0xc420070c60, 0xc420196120, 0x14, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:498 +0x238
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedPeerManagerConnect(0xc420070c60, 0xc420196120, 0x14)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peersmanager.go:13 +0x120
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentPeerManager.func1(0xc4201c2060, 0xc420070c60, 0xc420196120, 0x14)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peersmanager.go:147 +0xb9
created by github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentPeerManager
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peersmanager.go:148 +0x5eb

goroutine 34 [select]:
net.(*Dialer).DialContext.func1(0xc42014c2a0, 0xc4201e2a30, 0x19e6b20, 0xc4201c0200)
	/usr/local/go/src/net/dial.go:331 +0x111
created by net.(*Dialer).DialContext
	/usr/local/go/src/net/dial.go:336 +0xadb

goroutine 35 [select]:
net.(*netFD).connect.func2(0x19e6b20, 0xc4201c0200, 0xc420228000, 0xc4201c2300, 0xc4201c22a0)
	/usr/local/go/src/net/fd_unix.go:133 +0x1d5
created by net.(*netFD).connect
	/usr/local/go/src/net/fd_unix.go:144 +0x239

goroutine 14 [sleep]:
time.Sleep(0x2540be400)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc420139b80, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:623 +0x1e2
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc42024aa40, 0xc420139b80, 0x19e9ba0, 0xc420070c60)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3fd
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:182 +0x63a

goroutine 15 [select]:
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).threadedRegularSync(0xc420071080)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:38 +0x198
created by github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:126 +0x3ef

Any help would be greatly appreciated.

**Comment by tbenz9** [comment]
`SIGBUS` indicates that your disk may have errors. Follow these instructions to check for errors:

- [Windows](http://www.thewindowsclub.com/disk-error-checking-windows-8)
- [Mac](https://support.apple.com/en-us/HT201639)
- [Linux](https://www.tecmint.com/check-linux-hard-disk-bad-sectors-bad-blocks/) 

The next version of Sia will present this type of error in a more obvious way instead of crashing with a cryptic error message.
