### ISSUE TITLE
A critical error loading Sia has occured: Siad unexpectedly exited

### ISSUE THREAD

**Issue by rohillion** [NebulousLabs/Sia-UI#708]
MacBook Pro Sierra v10.12.6

Can't open the app. I imagine my laptop ran out of battery and interrupted the sync process. Here is the output when I open the app:

A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
unexpected fault address 0xa949a008
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0xa949a008 pc=0x132d3c9]

goroutine 1 [running]:
runtime.throw(0x16d0af7, 0x5)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc420465c38 sp=0xc420465c18
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:287 +0x1c8 fp=0xc420465c88 sp=0xc420465c38
github.com/NebulousLabs/bolt.(*Cursor).search(0xc420466218, 0xc4204662b8, 0x20, 0x20, 0xa6eb8)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:255 +0x69 fp=0xc420465d50 sp=0xc420465c88
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc420466218, 0xc4204662b8, 0x20, 0x20, 0x5164000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x156 fp=0xc420465de0 sp=0xc420465d50
github.com/NebulousLabs/bolt.(*Cursor).search(0xc420466218, 0xc4204662b8, 0x20, 0x20, 0x2b82)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1bb fp=0xc420465ea8 sp=0xc420465de0
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc420466218, 0xc4204662b8, 0x20, 0x20, 0x15f58000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x156 fp=0xc420465f38 sp=0xc420465ea8
github.com/NebulousLabs/bolt.(*Cursor).search(0xc420466218, 0xc4204662b8, 0x20, 0x20, 0x13976)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1bb fp=0xc420466000 sp=0xc420465f38
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc420466218, 0xc4204662b8, 0x20, 0x20, 0x1614d000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x156 fp=0xc420466090 sp=0xc420466000
github.com/NebulousLabs/bolt.(*Cursor).search(0xc420466218, 0xc4204662b8, 0x20, 0x20, 0x13b6b)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1bb fp=0xc420466158 sp=0xc420466090
github.com/NebulousLabs/bolt.(*Cursor).seek(0xc420466218, 0xc4204662b8, 0x20, 0x20, 0x0, 0x0, 0x12de7c3, 0xc4201100f8, 0xc4200ee540, 0x2, ...)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:159 +0xb1 fp=0xc4204661a8 sp=0xc420466158
github.com/NebulousLabs/bolt.(*Bucket).Get(0xc4230cf5c0, 0xc4204662b8, 0x20, 0x20, 0xc4230cf5c0, 0x23a82de337d672ba, 0x431b81e6151d172e)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:267 +0xef fp=0xc420466248 sp=0xc4204661a8
github.com/NebulousLabs/Sia/modules/consensus.getBlockMap(0xc4201100e0, 0xd902000000000000, 0x8b703be9b01f52b0, 0x199bf65428b18a44, 0x52c282b4eeca684c, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusdb.go:185 +0x7d fp=0xc4204662b0 sp=0xc420466248
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).computeConsensusChange(0xc420145b80, 0xc4201100e0, 0x0, 0x0, 0x0, 0xc4231db220, 0x1, 0x1, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:53 +0x818 fp=0xc420466eb0 sp=0xc4204662b0
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe.func2(0xc4201100e0, 0x17081f0, 0xc4201100e0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:172 +0xe0 fp=0xc420467190 sp=0xc420466eb0
github.com/NebulousLabs/bolt.(*DB).View(0xc420112780, 0xc42009f248, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:634 +0x9f fp=0xc4204671e0 sp=0xc420467190
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe(0xc420145b80, 0x19deca0, 0xc420081080, 0xc62214255be1cf9, 0xa4e335abdefd1b8b, 0x65af03ec71a97bde, 0x5adba08f75865ffa, 0x14d33c7, 0xd1c92115)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:180 +0x24f fp=0xc4204672c8 sp=0xc4204671e0
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).ConsensusSetSubscribe(0xc420145b80, 0x19deca0, 0xc420081080, 0xc62214255be1cf9, 0xa4e335abdefd1b8b, 0x65af03ec71a97bde, 0x5adba08f75865ffa, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:203 +0xee fp=0xc420467370 sp=0xc4204672c8
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist(0xc420081080, 0xc420081080, 0xc4202e4510)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:183 +0x944 fp=0xc4204675a8 sp=0xc420467370
github.com/NebulousLabs/Sia/modules/transactionpool.New(0x19ea7c0, 0xc420145b80, 0x19e9ba0, 0xc420080c60, 0xc420019a90, 0x46, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/transactionpool.go:101 +0x276 fp=0xc420467620 sp=0xc4204675a8
main.startDaemon(0x0, 0x0, 0x7fff5fbffd07, 0xe, 0x7fff5fbffd33, 0x5, 0x7fff5fbffd22, 0x5, 0x0, 0x7fff5fbffd8a, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:202 +0x1693 fp=0xc420467bd0 sp=0xc420467620
main.startDaemonCmd(0xc420089200, 0xc420019400, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:335 +0x162 fp=0xc420467cd0 sp=0xc420467bd0
github.com/spf13/cobra.(*Command).execute(0xc420089200, 0xc42000e0d0, 0x5, 0x5, 0xc420089200, 0xc42000e0d0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:653 +0x299 fp=0xc420467d88 sp=0xc420467cd0
github.com/spf13/cobra.(*Command).ExecuteC(0xc420089200, 0x16fce88, 0x3b, 0xc420154c80)
	/home/luke/go/src/github.com/spf13/cobra/command.go:728 +0x339 fp=0xc420467ed8 sp=0xc420467d88
github.com/spf13/cobra.(*Command).Execute(0xc420089200, 0x1aefba0, 0x16e58f7)
	/home/luke/go/src/github.com/spf13/cobra/command.go:687 +0x2b fp=0xc420467f08 sp=0xc420467ed8
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7aa fp=0xc420467f88 sp=0xc420467f08
runtime.main()
	/usr/local/go/src/runtime/proc.go:185 +0x20a fp=0xc420467fe0 sp=0xc420467f88
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420467fe8 sp=0xc420467fe0

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0xff
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [IO wait]:
net.runtime_pollWait(0x1c60060, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420156d18, 0x72, 0x0, 0xc4209a8040)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420156d18, 0xffffffffffffffff, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc420156cb0, 0x0, 0x19dffe0, 0xc4209a8040)
	/usr/local/go/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc42000c140, 0xc420040e70, 0x129d31e, 0x1054480)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc42000c140, 0x1708860, 0xc4200906e0, 0x19e6be0, 0xc4201660c0)
	/usr/local/go/src/net/tcpsock.go:228 +0x49
net/http.(*Server).Serve(0xc4200a6c60, 0x19e5f20, 0xc42000c140, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2643 +0x228
main.(*Server).Serve(0xc4200cb960, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/server.go:416 +0x44
main.startDaemon.func1(0xc420158240, 0xc4200cb960)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:145 +0x2b
created by main.startDaemon
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:146 +0x312

goroutine 7 [select]:
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedSaveLoop(0xc420080c60)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/persist.go:57 +0x122
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:249 +0x683

goroutine 8 [IO wait]:
net.runtime_pollWait(0x1c5ffa0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420156f48, 0x72, 0x0, 0xc420170060)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420156f48, 0xffffffffffffffff, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc420156ee0, 0x0, 0x19dffe0, 0xc420170060)
	/usr/local/go/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc42000c170, 0xc400000008, 0xc420164080, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc42000c170, 0x1708c50, 0xc420158300, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock.go:228 +0x49
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentListen(0xc420080c60, 0xc420158300)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:99 +0x75
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:294 +0xa23

goroutine 9 [select]:
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedSleep(0xc420080c60, 0x12a05f200, 0xc4201a00c0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:164 +0x121
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentPeerManager(0xc420080c60, 0xc420158360)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peersmanager.go:153 +0x608
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:301 +0xacf

goroutine 10 [select]:
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentNodeManager(0xc420080c60, 0xc4201583c0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/nodes.go:283 +0x5e0
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:308 +0xb7b

goroutine 11 [select]:
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentNodePurger(0xc420080c60, 0xc420158420)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/nodes.go:221 +0x650
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:315 +0xc27

goroutine 12 [sleep]:
time.Sleep(0xc91b2780)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/NebulousLabs/go-upnp.Discover(0xc400000008, 0x17081b0, 0xc420080d48)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/upnp.go:129 +0x55
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedForwardPort(0xc420080c60, 0xc420147035, 0x4)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/upnp.go:97 +0x8b
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:318 +0xc5e

goroutine 13 [sleep]:
time.Sleep(0xfdad6800)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/NebulousLabs/go-upnp.Discover(0xc400000008, 0x17081b0, 0xc420080d48)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/upnp.go:129 +0x55
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedLearnHostname(0xc420080c60)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/upnp.go:59 +0x8e
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:319 +0xc83

goroutine 18 [IO wait]:
net.runtime_pollWait(0x1c5fee0, 0x72, 0x9)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420216068, 0x72, 0x19e1ca0, 0x19dc448)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420216068, 0xc42072c040, 0x8)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc420216000, 0xc42072c040, 0x8, 0x8, 0x0, 0x19e1ca0, 0x19dc448)
	/usr/local/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc420730000, 0xc42072c040, 0x8, 0x8, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:181 +0x70
io.ReadAtLeast(0x1e3e028, 0xc420730000, 0xc42072c040, 0x8, 0x8, 0x8, 0x15865f7, 0x162cbc0, 0x1587223)
	/usr/local/go/src/io/io.go:307 +0xa9
io.ReadFull(0x1e3e028, 0xc420730000, 0xc42072c040, 0x8, 0x8, 0x8, 0x100c564, 0x1b0c3b0)
	/usr/local/go/src/io/io.go:325 +0x58
github.com/NebulousLabs/Sia/encoding.ReadPrefix(0x1e3e028, 0xc420730000, 0x64, 0x100d428, 0x162cbc0, 0x16b2fa0, 0x0, 0x1e3e028)
	/home/luke/go/src/github.com/NebulousLabs/Sia/encoding/prefix.go:13 +0x97
github.com/NebulousLabs/Sia/encoding.ReadObject(0x1e3e028, 0xc420730000, 0x15d87c0, 0xc42072c010, 0x64, 0x0, 0xc420730000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/encoding/prefix.go:28 +0x43
github.com/NebulousLabs/Sia/modules/gateway.connectVersionHandshake(0x19e9620, 0xc420730000, 0x16cfdcd, 0x5, 0xc420730000, 0x0, 0x0, 0xc4201ac000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:368 +0x256
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedConnect(0xc420080c60, 0xc420185400, 0x11, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:504 +0x288
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedPeerManagerConnect(0xc420080c60, 0xc420185400, 0x11)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peersmanager.go:13 +0x120
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentPeerManager.func1(0xc4201a00c0, 0xc420080c60, 0xc420185400, 0x11)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peersmanager.go:147 +0xb9
created by github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentPeerManager
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peersmanager.go:148 +0x5eb

goroutine 14 [sleep]:
time.Sleep(0x2540be400)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc420145b80, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:623 +0x1e2
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc420256e60, 0xc420145b80, 0x19e9ba0, 0xc420080c60)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3fd
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:182 +0x63a

goroutine 28 [select]:
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).threadedRegularSync(0xc420081080)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:38 +0x198
created by github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:126 +0x3ef

**Comment by tbenz9** [comment]
`SIGBUS` indicates that your disk may have errors. Follow these instructions to check for errors:

- [Windows](http://www.thewindowsclub.com/disk-error-checking-windows-8)
- [Mac](https://support.apple.com/en-us/HT201639)
- [Linux](https://www.tecmint.com/check-linux-hard-disk-bad-sectors-bad-blocks/) 

The next version of Sia will present this type of error in a more obvious way instead of crashing with a cryptic error message.
