### ISSUE TITLE
  Error at startup Sia v1.3.1 (Windows 10) 

### ISSUE THREAD

**Issue by helsins** [NebulousLabs/Sia-UI#751]
I used the version 1.2.2 before, and I just downloaded the version 1.3.1.           
After closing version 1.2.2 and restarting windows, run version 1.3.1, with the following error:
 
A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
difficulty adjustment hardfork incompatibility detected

**Comment by helsins** [comment]
I now run version 1.2.2, and I also have the same wrong hints! But before running 1.3.1, 1.2.2 is normal.

**Comment by hq7878** [comment]
I'm also having a problem with 1.3.1 on Windows 10. Never used any other version before:

A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
Exception 0xc0000005 0x0 0x8204 0x18000890b
PC=0x18000890b

syscall.Syscall(0x7ff899d8bfd0, 0x2, 0x20c, 0x2, 0x0, 0x1e0, 0xa4a320, 0x64205b138)
	/usr/local/go/src/runtime/syscall_windows.go:163 +0x69
syscall.SetFileCompletionNotificationModes(0x20c, 0x2, 0xab573e, 0x4)
	/usr/local/go/src/syscall/zsyscall_windows.go:1727 +0x6f
internal/poll.(*FD).Init(0xc04205cd20, 0xab573e, 0x4, 0xaf1e50, 0x20c, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_windows.go:346 +0xf9
os.newFile(0x20c, 0xc0420129b0, 0x49, 0xab573e, 0x4, 0x0)
	/usr/local/go/src/os/file_windows.go:57 +0x138
os.openFile(0xc0420129b0, 0x49, 0x441, 0x1b0, 0x0, 0xc0420129b0, 0x0)
	/usr/local/go/src/os/file_windows.go:98 +0xff
os.OpenFile(0xc0420129b0, 0x49, 0x441, 0x1b0, 0xc04205b488, 0x2, 0x2)
	/usr/local/go/src/os/file_windows.go:159 +0x15e
github.com/NebulousLabs/Sia/persist.NewFileLogger(0xc0420129b0, 0x49, 0x2, 0xc0420129b0, 0x49)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:122 +0x51
github.com/NebulousLabs/Sia/modules/gateway.New(0xc04200e10b, 0x5, 0x1, 0xc04200a700, 0x3d, 0x19, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:211 +0x2f0
main.(*Server).loadModules(0xc0420824b0, 0xaf1aa0, 0xc0420824b0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/server.go:465 +0x2365
main.startDaemon(0x0, 0x0, 0xc04200c2cb, 0xe, 0xc04200e10b, 0x5, 0xc04200c30c, 0x5, 0x0, 0xc04200e14a, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:164 +0x1ae
main.startDaemonCmd(0xc0420b0d80, 0xc042086410, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:209 +0x169
github.com/spf13/cobra.(*Command).execute(0xc0420b0d80, 0xc042062010, 0x5, 0x7, 0xc0420b0d80, 0xc042062010)
	/home/luke/go/src/github.com/spf13/cobra/command.go:750 +0x2c8
github.com/spf13/cobra.(*Command).ExecuteC(0xc0420b0d80, 0xae2c79, 0x3b, 0xc042041a40)
	/home/luke/go/src/github.com/spf13/cobra/command.go:831 +0x315
github.com/spf13/cobra.(*Command).Execute(0xc0420b0d80, 0xefcd80, 0xacaf03)
	/home/luke/go/src/github.com/spf13/cobra/command.go:784 +0x32
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/main.go:174 +0x797

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:131 +0xad
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x29
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x48

goroutine 6 [IO wait]:
internal/poll.runtime_pollWait(0x1135060, 0x72, 0xc0420b1698)
	/usr/local/go/src/runtime/netpoll.go:173 +0x5e
internal/poll.(*pollDesc).wait(0xc0420b17d8, 0x72, 0xde1500, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xb5
internal/poll.(*ioSrv).ExecIO(0xef9158, 0xc0420b1698, 0xc04216a000, 0x2, 0x1, 0x0)
	/usr/local/go/src/internal/poll/fd_windows.go:195 +0x13a
internal/poll.(*FD).acceptOne(0xc0420b1680, 0x21c, 0xc042168000, 0x2, 0x2, 0xc0420b1698, 0x180d50, 0xc04214fd08, 0x41194f, 0x10)
	/usr/local/go/src/internal/poll/fd_windows.go:748 +0xae
internal/poll.(*FD).Accept(0xc0420b1680, 0xc04215e040, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/internal/poll/fd_windows.go:782 +0x171
net.(*netFD).accept(0xc0420b1680, 0x41194f, 0x30, 0xa64440)
	/usr/local/go/src/net/fd_windows.go:192 +0x88
net.(*TCPListener).accept(0xc0420040e8, 0x58e781, 0xa64440, 0xc04215c090)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x35
net.(*TCPListener).Accept(0xc0420040e8, 0xc04200e1a8, 0x9ff480, 0xec53d0, 0xa9f1c0)
	/usr/local/go/src/net/tcpsock.go:247 +0x50
net/http.(*Server).Serve(0xc04206b110, 0xdea700, 0xc0420040e8, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2695 +0x1b9
main.(*Server).Serve(0xc0420824b0, 0xe, 0xc04200e10b)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/server.go:578 +0x4b
created by main.startDaemon
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:163 +0x19d
rax     0x0
rbx     0xefdae0
rcx     0x20c
rdi     0x317000
rsi     0xc04205b070
rbp     0xc04205b020
rsp     0x112fd80
r8      0x0
r9      0x20c
r10     0x12a2df0
r11     0x128ede8
r12     0x0
r13     0xfa
r14     0xfa
r15     0xa
rip     0x18000890b
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b

**Comment by nip10** [comment]
Im having the same problem as OP.
Always used v1.2.2 until 2 days ago when I (tried) started using v1.3.1.
Windows 10 x64

**Comment by theoxrocks99** [comment]
I am also having the same issue.  Windows 10, updated from 1.22, has not worked for me at all since update.
A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
difficulty adjustment hardfork incompatibility detected

**Comment by Swipe514** [comment]
Same as above.

**Comment by CapitalBoo** [comment]
I am having the same issue/error as OP

**Comment by dadoow** [comment]
Same problem here

**Comment by CapitalBoo** [comment]
I ran into the same issue and was able to resolve it by reading through the following blog post and deleting consensus.db : https://blog.sia.tech/troubleshooting-the-recent-hardfork-ca77e0b17f0f

**Comment by Marc90521** [comment]
You can close this issue I think! The solve by @CapitalBoo worked for me.

> First, delete the consensus.db file. It is located in:

> Windows: `Users\<user>\appdata\roaming\Sia-UI\sia\consensus\consensus.db`
> OS X: `$HOME/Library/Application Support/Sia-UI/sia/consensus/consensus.db`
> Linux: `$HOME/.config/Sia-UI/sia/consensus/consensus.db`

Note: you do have to do the complete synchronization again. Takes a little while as you have to dl 8gig as of now.
